<?php

return [
    'profiles' => [
        'distribution' => [
            'label' => 'پخش و فروش کالا',
            'description' => 'مناسب پخش مرغ و گوشت، میوه، دارو، مواد غذایی و هر کالایی که هم تعدادی (کارتن/جزء) و هم وزنی فروخته می‌شود',
            'quantity_mode' => 'physical',
            'default_labels' => [
                'pack' => 'کارتن',
                'tedad' => 'عدد',
                'total_qty' => 'کل',
                'weight' => 'وزن (کیلو)',
                'unit_price' => 'فی واحد',
            ],
            'columns' => [
                ['key' => 'row', 'type' => 'row'],
                ['key' => 'sku', 'type' => 'field', 'toggle' => 'column_pr_code'],
                ['key' => 'title', 'type' => 'field', 'always' => true],
                ['key' => 'moadian', 'type' => 'static', 'toggle' => 'column_moadian'],
                ['key' => 'pack', 'type' => 'field', 'toggle' => 'column_sub_unit', 'sum' => true],
                ['key' => 'tedad', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'total_qty', 'type' => 'computed', 'toggle' => 'column_sub_unit', 'sum' => true],
                ['key' => 'weight', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'unit_price', 'type' => 'field', 'always' => true],
                ['key' => 'gross', 'type' => 'computed', 'always' => true, 'sum' => true],
                ['key' => 'discount_percent', 'type' => 'field', 'toggle' => 'column_discount'],
                ['key' => 'discount_amount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'after_discount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'tax', 'type' => 'computed', 'toggle' => 'column_tax', 'sum' => true],
                ['key' => 'net', 'type' => 'computed', 'always' => true, 'sum' => true],
            ],
        ],
        'education' => [
            'label' => 'خدمات آموزشی',
            'description' => 'مناسب دوره، سرفصل و فروش بر اساس تعداد نفر',
            'quantity_mode' => 'count',
            'default_labels' => [
                'course' => 'دوره / محصول',
                'section' => 'سرفصل',
                'participants' => 'تعداد نفر',
                'unit_price' => 'فی نفر',
            ],
            'columns' => [
                ['key' => 'row', 'type' => 'row'],
                ['key' => 'course', 'type' => 'field', 'always' => true],
                ['key' => 'section', 'type' => 'field', 'always' => true],
                ['key' => 'participants', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'unit_price', 'type' => 'field', 'always' => true],
                ['key' => 'gross', 'type' => 'computed', 'always' => true, 'sum' => true],
                ['key' => 'discount_percent', 'type' => 'field', 'toggle' => 'column_discount'],
                ['key' => 'discount_amount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'after_discount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'tax', 'type' => 'computed', 'toggle' => 'column_tax', 'sum' => true],
                ['key' => 'net', 'type' => 'computed', 'always' => true, 'sum' => true],
            ],
        ],
        'subscription' => [
            'label' => 'اشتراک / SaaS',
            'description' => 'مناسب پلن، مدت اشتراک و تعداد کاربر',
            'quantity_mode' => 'subscription',
            'default_labels' => [
                'plan' => 'پلن / محصول',
                'duration' => 'مدت (ماه)',
                'seats' => 'تعداد کاربر',
                'unit_price' => 'فی ماهانه',
            ],
            'columns' => [
                ['key' => 'row', 'type' => 'row'],
                ['key' => 'plan', 'type' => 'field', 'always' => true],
                ['key' => 'duration', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'seats', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'billing_units', 'type' => 'computed', 'always' => true, 'sum' => true],
                ['key' => 'unit_price', 'type' => 'field', 'always' => true],
                ['key' => 'gross', 'type' => 'computed', 'always' => true, 'sum' => true],
                ['key' => 'discount_percent', 'type' => 'field', 'toggle' => 'column_discount'],
                ['key' => 'discount_amount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'after_discount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'tax', 'type' => 'computed', 'toggle' => 'column_tax', 'sum' => true],
                ['key' => 'net', 'type' => 'computed', 'always' => true, 'sum' => true],
            ],
        ],
        'bulk_weight' => [
            'label' => 'کالای وزنی / فله',
            'description' => 'مناسب فروش بر اساس وزن خالص: میوه، حبوبات، آهن، مصالح و مواد فله',
            'quantity_mode' => 'weight',
            'default_labels' => [
                'weight' => 'وزن (کیلو)',
                'unit_price' => 'فی هر کیلو',
            ],
            'columns' => [
                ['key' => 'row', 'type' => 'row'],
                ['key' => 'sku', 'type' => 'field', 'toggle' => 'column_pr_code'],
                ['key' => 'title', 'type' => 'field', 'always' => true],
                ['key' => 'moadian', 'type' => 'static', 'toggle' => 'column_moadian'],
                ['key' => 'weight', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'unit_price', 'type' => 'field', 'always' => true],
                ['key' => 'gross', 'type' => 'computed', 'always' => true, 'sum' => true],
                ['key' => 'discount_percent', 'type' => 'field', 'toggle' => 'column_discount'],
                ['key' => 'discount_amount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'after_discount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'tax', 'type' => 'computed', 'toggle' => 'column_tax', 'sum' => true],
                ['key' => 'net', 'type' => 'computed', 'always' => true, 'sum' => true],
            ],
        ],
        'virtual' => [
            'label' => 'محصولات مجازی / دیجیتال',
            'description' => 'مناسب کالای بدون وزن و انبار: لایسنس، کد شارژ، فایل، گیفت‌کارت',
            'quantity_mode' => 'count',
            'default_labels' => [
                'tedad' => 'تعداد',
                'unit_price' => 'فی واحد',
            ],
            'columns' => [
                ['key' => 'row', 'type' => 'row'],
                ['key' => 'sku', 'type' => 'field', 'toggle' => 'column_pr_code'],
                ['key' => 'title', 'type' => 'field', 'always' => true],
                ['key' => 'moadian', 'type' => 'static', 'toggle' => 'column_moadian'],
                ['key' => 'tedad', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'unit_price', 'type' => 'field', 'always' => true],
                ['key' => 'gross', 'type' => 'computed', 'always' => true, 'sum' => true],
                ['key' => 'discount_percent', 'type' => 'field', 'toggle' => 'column_discount'],
                ['key' => 'discount_amount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'after_discount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'tax', 'type' => 'computed', 'toggle' => 'column_tax', 'sum' => true],
                ['key' => 'net', 'type' => 'computed', 'always' => true, 'sum' => true],
            ],
        ],
        'service' => [
            'label' => 'خدمات',
            'description' => 'مناسب خدمات قابل ارائه: تعمیر، نصب، مشاوره، حمل و نقل',
            'quantity_mode' => 'count',
            'default_labels' => [
                'tedad' => 'تعداد / دفعات',
                'unit_price' => 'فی خدمت',
            ],
            'columns' => [
                ['key' => 'row', 'type' => 'row'],
                ['key' => 'title', 'type' => 'field', 'always' => true],
                ['key' => 'moadian', 'type' => 'static', 'toggle' => 'column_moadian'],
                ['key' => 'tedad', 'type' => 'field', 'always' => true, 'sum' => true],
                ['key' => 'unit_price', 'type' => 'field', 'always' => true],
                ['key' => 'gross', 'type' => 'computed', 'always' => true, 'sum' => true],
                ['key' => 'discount_percent', 'type' => 'field', 'toggle' => 'column_discount'],
                ['key' => 'discount_amount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'after_discount', 'type' => 'computed', 'toggle' => 'column_discount', 'sum' => true],
                ['key' => 'tax', 'type' => 'computed', 'toggle' => 'column_tax', 'sum' => true],
                ['key' => 'net', 'type' => 'computed', 'always' => true, 'sum' => true],
            ],
        ],
    ],

    // پروفایل‌های قدیمی که به پروفایل جدید نگاشت می‌شوند
    'legacy_profile_map' => [
        'weight' => 'distribution',
    ],

    'column_labels' => [
        'row' => 'ردیف',
        'sku' => 'کد کالا',
        'title' => 'نام کالا',
        'moadian' => 'شناسه مودیان',
        'pack' => 'واحد فرعی',
        'tedad' => 'واحد اصلی',
        'total_qty' => 'جمع کل',
        'weight' => 'وزن',
        'course' => 'دوره / محصول',
        'section' => 'سرفصل',
        'participants' => 'تعداد نفر',
        'plan' => 'پلن / محصول',
        'duration' => 'مدت (ماه)',
        'seats' => 'تعداد کاربر',
        'billing_units' => 'واحد صورتحساب',
        'unit_price' => 'فی واحد',
        'gross' => 'مبلغ ناخالص',
        'discount_percent' => 'درصد تخفیف',
        'discount_amount' => 'مبلغ تخفیف',
        'after_discount' => 'مبلغ پس از تخفیف',
        'tax' => 'مالیات',
        'net' => 'مبلغ خالص',
    ],

    /*
    | برچسب ستون‌های قابل سفارشی در فاکتورساز — عنوان، راهنما و پیشنهادهای آماده
    */
    'label_field_meta' => [
        'pack' => [
            'group' => 'unit',
            'group_label' => 'ستون‌های واحد',
            'title' => 'نام ستون واحد فرعی',
            'hint' => 'واحد بسته‌بندی بزرگ‌تر: کارتن، جعبه، پک، بسته، کیسه، پالت، تن ...',
            'presets' => ['کارتن', 'جعبه', 'پک', 'بسته', 'کیسه', 'پالت', 'تن', 'قوطی بزرگ'],
        ],
        'tedad' => [
            'group' => 'unit',
            'group_label' => 'ستون‌های واحد',
            'title' => 'نام ستون واحد اصلی',
            'hint' => 'واحد جزئی یا پایه: عدد، بطری، قرص، قطعه، رول، جزء، شماره ...',
            'presets' => ['عدد', 'جزء', 'بطری', 'قرص', 'قوطی', 'قطعه', 'رول', 'شماره', 'بسته کوچک'],
        ],
        'total_qty' => [
            'group' => 'unit',
            'group_label' => 'ستون‌های واحد',
            'title' => 'نام ستون جمع کل',
            'hint' => 'مجموع به واحد پایه (مثلاً کل عدد، کل بطری، کل گرم)',
            'presets' => ['کل', 'جمع', 'مجموع', 'کل (عدد)', 'کل واحد'],
        ],
        'weight' => [
            'group' => 'unit',
            'group_label' => 'ستون‌های واحد',
            'title' => 'نام ستون وزن',
            'hint' => 'اگر فروش وزنی دارید، واحد را در عنوان ستون بنویسید',
            'presets' => [
                'وزن (کیلو)',
                'وزن (گرم)',
                'وزن (تن)',
                'وزن خالص (کیلو)',
                'وزن خالص (گرم)',
                'میلی‌گرم',
                'سوت',
            ],
        ],
        'unit_price' => [
            'group' => 'pricing',
            'group_label' => 'قیمت‌گذاری',
            'title' => 'نام ستون فی واحد',
            'hint' => 'متناسب با واحد فروش: فی هر عدد، فی هر بطری، فی هر کیلو ...',
            'presets' => ['فی واحد', 'فی هر عدد', 'فی هر بطری', 'فی هر کیلو', 'فی هر گرم', 'فی هر کارتن', 'فی هر جعبه'],
        ],
        'course' => [
            'group' => 'content',
            'group_label' => 'محتوای خط فاکتور',
            'title' => 'نام ستون دوره / محصول',
            'hint' => '',
            'presets' => ['دوره', 'محصول', 'دوره / محصول', 'خدمت'],
        ],
        'section' => [
            'group' => 'content',
            'group_label' => 'محتوای خط فاکتور',
            'title' => 'نام ستون سرفصل',
            'hint' => '',
            'presets' => ['سرفصل', 'فصل', 'جلسه', 'موضوع'],
        ],
        'participants' => [
            'group' => 'content',
            'group_label' => 'محتوای خط فاکتور',
            'title' => 'نام ستون تعداد نفر',
            'hint' => '',
            'presets' => ['تعداد نفر', 'نفر', 'شرکت‌کننده', 'ظرفیت'],
        ],
        'plan' => [
            'group' => 'content',
            'group_label' => 'محتوای خط فاکتور',
            'title' => 'نام ستون پلن',
            'hint' => '',
            'presets' => ['پلن', 'پلن / محصول', 'اشتراک', 'بسته سرویس'],
        ],
        'duration' => [
            'group' => 'content',
            'group_label' => 'محتوای خط فاکتور',
            'title' => 'نام ستون مدت',
            'hint' => '',
            'presets' => ['مدت (ماه)', 'مدت', 'دوره اشتراک', 'ماه'],
        ],
        'seats' => [
            'group' => 'content',
            'group_label' => 'محتوای خط فاکتور',
            'title' => 'نام ستون تعداد کاربر',
            'hint' => '',
            'presets' => ['تعداد کاربر', 'کاربر', 'صندلی', 'لایسنس'],
        ],
    ],

    'label_field_groups' => [
        'unit' => 'برچسب ستون‌های واحد (اصلی، فرعی، وزن و جمع)',
        'pricing' => 'برچسب قیمت‌گذاری',
        'content' => 'برچسب سایر ستون‌ها',
        'other' => 'سایر برچسب‌ها',
    ],
];
