<?php

return [
    'definitions' => [
        'feature_area_management' => [
            'group' => 'sales_workflow',
            'type' => 'boolean',
            'label' => 'منطقه بندی مشتریان',
            'default' => 'yes',
        ],
        'feature_route_management' => [
            'group' => 'sales_workflow',
            'type' => 'boolean',
            'label' => 'مسیر فروش و ویزیت روزانه',
            'default' => 'yes',
        ],
        'feature_visitor_management' => [
            'group' => 'sales_workflow',
            'type' => 'boolean',
            'label' => 'مدیریت ویزیتورها',
            'default' => 'yes',
        ],
        'feature_direct_customer_registration' => [
            'group' => 'sales_workflow',
            'type' => 'boolean',
            'label' => 'ثبت مستقیم مشتری بدون مسیر',
            'default' => 'yes',
        ],
        'feature_branch_management' => [
            'group' => 'sales_workflow',
            'type' => 'boolean',
            'label' => 'شعب و واحدهای پخش',
            'default' => 'yes',
        ],
        'feature_city_management' => [
            'group' => 'sales_workflow',
            'type' => 'boolean',
            'label' => 'شهرها',
            'default' => 'yes',
        ],
        'feature_distribution' => [
            'group' => 'logistics',
            'type' => 'boolean',
            'label' => 'پخش و تحویل کالا',
            'default' => 'yes',
        ],
        'feature_agency_sales' => [
            'group' => 'logistics',
            'type' => 'boolean',
            'label' => 'پنل نمایندگی و شعب',
            'default' => 'no',
        ],
        'feature_multi_warehouse' => [
            'group' => 'warehouse',
            'type' => 'boolean',
            'label' => 'انتقال بین انبارها',
            'default' => 'yes',
        ],
        'feature_warehouse_management' => [
            'group' => 'warehouse',
            'type' => 'boolean',
            'label' => 'مدیریت انبار و موجودی',
            'default' => 'yes',
        ],
        'warehouse_location_mode' => [
            'group' => 'warehouse',
            'type' => 'select',
            'label' => 'روش استفاده از قفسه و مکان انبار',
            'default' => 'optional_locations',
            'options' => [
                'store_only' => 'فقط سطح انبار، بدون قفسه',
                'optional_locations' => 'قفسه اختیاری برای هر ردیف',
                'required_locations' => 'قفسه اجباری برای هر ردیف',
            ],
        ],
        'feature_multi_price' => [
            'group' => 'warehouse',
            'type' => 'boolean',
            'label' => 'چند سطح قیمت',
            'default' => 'yes',
        ],
        'feature_sales_targets' => [
            'group' => 'management',
            'type' => 'boolean',
            'label' => 'تارگت گذاری فروش',
            'default' => 'yes',
        ],
        'feature_commission' => [
            'group' => 'management',
            'type' => 'boolean',
            'label' => 'پورسانت و پاداش',
            'default' => 'no',
        ],
        'feature_customer_credit' => [
            'group' => 'finance',
            'type' => 'boolean',
            'label' => 'سقف اعتبار مشتری',
            'default' => 'yes',
        ],
        'feature_double_entry_accounting' => [
            'group' => 'finance',
            'type' => 'boolean',
            'label' => 'حسابداری دوبل',
            'default' => 'yes',
        ],
        'feature_manager_order_approval' => [
            'group' => 'approval',
            'type' => 'boolean',
            'label' => 'تایید مدیریتی سفارش ها',
            'default' => 'yes',
        ],
        'sales_inventory_policy' => [
            'group' => 'sales_workflow',
            'type' => 'select',
            'label' => 'نوع فروش نسبت به موجودی',
            'default' => 'stock_based',
            'options' => [
                'stock_based' => 'فروش موجودی محور و خروج از موجودی',
                'preorder_supply' => 'پیش سفارش و تامین بر اساس سفارش',
                'hybrid' => 'ترکیبی، سفارش و خروج انبار همزمان',
            ],
        ],
        'feature_gps_tracking' => [
            'group' => 'logistics',
            'type' => 'boolean',
            'label' => 'ثبت موقعیت GPS',
            'default' => 'no',
        ],
        'currency_type' => [
            'group' => 'finance',
            'type' => 'select',
            'label' => 'واحد پول',
            'default' => 'rial',
            'options' => [
                'rial' => 'ریال',
                'toman' => 'تومان',
            ],
        ],
        'tax_percent' => [
            'group' => 'finance',
            'type' => 'number',
            'label' => 'درصد مالیات',
            'default' => '0',
        ],
        'vat_percent' => [
            'group' => 'finance',
            'type' => 'number',
            'label' => 'درصد ارزش افزوده',
            'default' => '0',
        ],
        'inventory_costing_method' => [
            'group' => 'warehouse',
            'type' => 'select',
            'label' => 'روش قیمت گذاری موجودی',
            'default' => 'weighted_average',
            'options' => [
                'weighted_average' => 'میانگین موزون',
                'fifo' => 'FIFO',
                'fixed_price' => 'قیمت ثابت',
                'last_purchase' => 'آخرین خرید',
            ],
        ],
        'customer_creation_mode' => [
            'group' => 'sales_workflow',
            'type' => 'multiselect',
            'label' => 'روش های مجاز ثبت مشتری',
            'default' => ['route_based'],
            'options' => [
                'route_based' => 'بر اساس منطقه و مسیر',
                'direct' => 'ثبت مستقیم',
                'agency_based' => 'بر اساس نماینده',
            ],
        ],
        'sales_scenario_template' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'قالب سناریوی فروش',
            'default' => 'standard_distribution',
            'options' => [
                'standard_distribution' => 'پخش استاندارد با تایید مدیریتی',
                'direct_sales' => 'فروش مستقیم و تایید سریع',
                'marketer_based' => 'بازاریاب محور با کنترل سرپرست',
                'sales_support_based' => 'ثبت توسط پشتیبان فروش',
                'b2b_quote' => 'فروش B2B با پیش فاکتور',
                'agency_branch' => 'فروش نمایندگی و شعبه ای',
                'ecommerce' => 'فروش اینترنتی',
                'project_contract' => 'فروش پروژه ای یا قراردادی',
                'multi_step_control' => 'کنترل چند مرحله ای فروش، انبار و حسابداری',
                'custom' => 'سناریوی اختصاصی',
            ],
        ],
        'sales_process_entry_point' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'نقطه شروع فرآیند فروش',
            'default' => 'sales_order',
            'options' => [
                'lead' => 'سرنخ CRM',
                'opportunity' => 'فرصت فروش',
                'quote' => 'پیش فاکتور',
                'sales_order' => 'سفارش فروش',
                'invoice' => 'فاکتور فروش',
            ],
        ],
        'sales_document_flow' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'مراحل فعال در مسیر فروش',
            'default' => ['customer', 'invoice', 'approval', 'warehouse', 'accounting', 'delivery', 'crm_followup'],
            'options' => [
                'lead' => 'سرنخ CRM',
                'opportunity' => 'فرصت فروش',
                'customer' => 'ثبت یا انتخاب مشتری',
                'quote' => 'پیش فاکتور',
                'sales_order' => 'سفارش فروش',
                'invoice' => 'فاکتور فروش',
                'approval' => 'تایید فروش',
                'warehouse' => 'رزرو و خروج انبار',
                'settlement' => 'دریافت و تسویه',
                'accounting' => 'سند حسابداری',
                'delivery' => 'تحویل یا پخش',
                'crm_followup' => 'پیگیری CRM بعد از فروش',
            ],
        ],
        'invoice_creation_roles' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'نقش های مجاز برای ثبت فاکتور یا سفارش',
            'default' => ['all'],
            'options' => [
                'all' => 'همه کاربران دارای دسترسی فاکتور',
                'visitor' => 'بازاریاب / ویزیتور',
                'sales_support' => 'پشتیبان فروش',
                'expert' => 'کارشناس فروش',
                'leader' => 'سرپرست فروش',
                'sales_manager' => 'مدیر فروش',
                'panel_manager' => 'مدیر پنل',
                'god' => 'مدیر کل سیستم',
            ],
        ],
        'invoice_approval_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'روش تایید فاکتور یا سفارش',
            'default' => 'legacy_toggle',
            'options' => [
                'legacy_toggle' => 'بر اساس کلید فعلی تایید مدیریتی سفارش ها',
                'auto' => 'تایید خودکار بعد از ثبت',
                'supervisor' => 'تایید سرپرست فروش',
                'sales_expert' => 'تایید کارشناس فروش',
                'sales_manager' => 'تایید مدیر فروش',
                'general_manager' => 'تایید مدیر کل پنل',
                'multi_step' => 'تایید چند مرحله ای',
            ],
        ],
        'invoice_approval_roles' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'نقش های مجاز برای تایید فاکتور',
            'default' => ['leader', 'panel_manager'],
            'options' => [
                'leader' => 'سرپرست فروش',
                'sales_expert' => 'کارشناس فروش',
                'sales_manager' => 'مدیر فروش',
                'accountant' => 'حسابدار',
                'panel_manager' => 'مدیر پنل',
                'god' => 'مدیر کل سیستم',
            ],
        ],
        'customer_creation_roles' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'نقش های مجاز برای ثبت مشتری',
            'default' => ['all'],
            'options' => [
                'all' => 'همه کاربران دارای دسترسی مشتری',
                'visitor' => 'بازاریاب / ویزیتور',
                'sales_support' => 'پشتیبان فروش',
                'expert' => 'کارشناس فروش',
                'leader' => 'سرپرست فروش',
                'sales_manager' => 'مدیر فروش',
                'panel_manager' => 'مدیر پنل',
            ],
        ],
        'customer_approval_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'روش تایید مشتری جدید',
            'default' => 'auto',
            'options' => [
                'auto' => 'ثبت و تایید خودکار',
                'supervisor' => 'نیازمند تایید سرپرست',
                'sales_manager' => 'نیازمند تایید مدیر فروش',
                'panel_manager' => 'نیازمند تایید مدیر پنل',
            ],
        ],
        'invoice_prerequisites' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'شروط اجباری قبل از ثبت فاکتور',
            'default' => ['active_customer', 'price_list'],
            'options' => [
                'active_customer' => 'مشتری فعال و تایید شده باشد',
                'legal_info' => 'کد اقتصادی یا شناسه ملی مشتری کامل باشد',
                'route_region' => 'منطقه و مسیر مشتری مشخص باشد',
                'credit_limit' => 'سقف اعتبار مشتری کنترل شود',
                'price_list' => 'قیمت از لیست قیمت مجاز خوانده شود',
                'available_inventory' => 'موجودی آزاد کالا کنترل شود',
                'crm_followup' => 'پیگیری CRM قبل از فاکتور ثبت شده باشد',
                'opportunity_stage' => 'فرصت فروش به مرحله مجاز رسیده باشد',
                'approved_quote' => 'پیش فاکتور تایید شده وجود داشته باشد',
            ],
        ],
        'price_control_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'روش کنترل قیمت فروش',
            'default' => 'price_list',
            'options' => [
                'product_default' => 'فقط قیمت پیش فرض کالا',
                'price_list' => 'لیست قیمت مجاز پنل',
                'customer_price_list' => 'لیست قیمت اختصاصی مشتری',
                'role_based' => 'سطح قیمت بر اساس نقش کاربر',
                'manual_with_approval' => 'تغییر دستی با تایید',
            ],
        ],
        'max_discount_without_approval_percent' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'حداکثر تخفیف بدون تایید درصد',
            'default' => '0',
        ],
        'min_profit_margin_percent' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'حداقل حاشیه سود مجاز درصد',
            'default' => '0',
        ],
        'amount_supervisor_threshold' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'آستانه مبلغ برای تایید سرپرست',
            'default' => '0',
        ],
        'amount_manager_threshold' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'آستانه مبلغ برای تایید مدیر فروش یا مدیر پنل',
            'default' => '0',
        ],
        'customer_credit_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'سیاست اعتبار مشتری',
            'default' => 'warning',
            'options' => [
                'ignore' => 'کنترل نشود',
                'warning' => 'فقط هشدار',
                'accountant_approval' => 'نیازمند تایید حسابدار',
                'manager_approval' => 'نیازمند تایید مدیر پنل',
                'block_invoice' => 'جلوگیری از تایید فاکتور',
            ],
        ],
        'credit_exposure_formula' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'اجزای فرمول ریسک اعتبار مشتری',
            'default' => ['open_invoices', 'open_cheques', 'new_invoice'],
            'options' => [
                'customer_balance' => 'مانده حساب مشتری',
                'open_invoices' => 'فاکتورهای تسویه نشده',
                'open_cheques' => 'چک های باز',
                'overdue_debt' => 'بدهی سررسید گذشته',
                'new_invoice' => 'مبلغ فاکتور جدید',
            ],
        ],
        'overdue_debt_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'رفتار سیستم با بدهی سررسید گذشته',
            'default' => 'accountant_approval',
            'options' => [
                'ignore' => 'نادیده گرفته شود',
                'warning' => 'فقط هشدار',
                'accountant_approval' => 'تایید حسابدار',
                'manager_approval' => 'تایید مدیر پنل',
                'block_invoice' => 'مسدود کردن تایید فاکتور',
            ],
        ],
        'open_cheque_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'رفتار سیستم با چک های باز مشتری',
            'default' => 'warning',
            'options' => [
                'ignore' => 'نادیده گرفته شود',
                'warning' => 'فقط هشدار',
                'accountant_approval' => 'تایید حسابدار',
                'manager_approval' => 'تایید مدیر پنل',
            ],
        ],
        'allowed_payment_types' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'روش های پرداخت مجاز فروش',
            'default' => ['cash', 'pos', 'cheque', 'credit'],
            'options' => [
                'cash' => 'نقدی',
                'pos' => 'کارتخوان یا درگاه',
                'cheque' => 'چک',
                'credit' => 'نسیه',
                'mixed' => 'ترکیبی',
                'installment' => 'اقساطی',
            ],
        ],
        'settlement_required_stage' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'مرحله الزام تسویه یا دریافت وجه',
            'default' => 'before_delivery',
            'options' => [
                'none' => 'الزام ندارد',
                'before_invoice_approval' => 'قبل از تایید فاکتور',
                'before_warehouse_issue' => 'قبل از خروج انبار',
                'before_delivery' => 'قبل از تحویل',
                'after_delivery' => 'بعد از تحویل قابل پیگیری باشد',
            ],
        ],
        'cheque_approval_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'سیاست تایید فروش چکی',
            'default' => 'accountant_approval',
            'options' => [
                'auto' => 'بدون تایید اضافه',
                'accountant_approval' => 'تایید حسابدار',
                'manager_approval' => 'تایید مدیر پنل',
                'block_until_cheque_registered' => 'تا ثبت چک تایید نشود',
            ],
        ],
        'inventory_check_stage' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'مرحله کنترل موجودی',
            'default' => 'before_invoice',
            'options' => [
                'none' => 'کنترل نشود',
                'before_invoice' => 'قبل از ثبت فاکتور',
                'before_approval' => 'قبل از تایید فروش',
                'before_reservation' => 'قبل از رزرو انبار',
                'before_issue' => 'قبل از خروج کالا',
            ],
        ],
        'inventory_reservation_stage' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'مرحله رزرو موجودی',
            'default' => 'after_approval',
            'options' => [
                'none' => 'رزرو انجام نشود',
                'after_invoice' => 'بعد از ثبت فاکتور',
                'after_approval' => 'بعد از تایید فروش',
                'manual_storekeeper' => 'دستی توسط انباردار',
            ],
        ],
        'shortage_handling_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'رفتار سیستم هنگام کمبود موجودی',
            'default' => 'manager_approval',
            'options' => [
                'allow_preorder' => 'اجازه پیش فروش',
                'warehouse_approval' => 'تایید انباردار',
                'manager_approval' => 'تایید مدیر انبار یا مدیر پنل',
                'block_invoice' => 'جلوگیری از تایید فاکتور',
            ],
        ],
        'partial_delivery_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'سیاست تحویل جزئی',
            'default' => 'allowed_with_trace',
            'options' => [
                'not_allowed' => 'مجاز نیست',
                'allowed_with_trace' => 'مجاز با ثبت مانده',
                'manager_approval' => 'نیازمند تایید مدیر',
            ],
        ],
        'warehouse_issue_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'شروع عملیات انبار بعد از فروش',
            'default' => 'after_invoice_approval',
            'options' => [
                'after_invoice_approval' => 'بعد از تایید فاکتور',
                'storekeeper_required' => 'با تایید انباردار',
                'manager_required' => 'با تایید مدیر انبار یا مدیر پنل',
                'manual' => 'کاملا دستی',
            ],
        ],
        'delivery_assignment_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'روش تخصیص تحویل و پخش',
            'default' => 'manual',
            'options' => [
                'manual' => 'تخصیص دستی',
                'route_based' => 'بر اساس مسیر مشتری',
                'driver_auto' => 'پیشنهاد خودکار راننده',
                'customer_pickup' => 'تحویل از انبار به مشتری',
                'carrier' => 'ارسال با باربری',
            ],
        ],
        'route_required_for_delivery' => [
            'group' => 'sales_scenario',
            'type' => 'boolean',
            'label' => 'الزام مسیر برای تحویل',
            'default' => 'no',
        ],
        'accounting_posting_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'ثبت حسابداری فروش',
            'default' => 'accountant_review',
            'options' => [
                'auto_after_approval' => 'خودکار بعد از تایید فروش',
                'accountant_review' => 'بعد از بررسی حسابدار',
                'manual' => 'ثبت دستی توسط حسابداری',
            ],
        ],
        'sales_accounting_posting_stage' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'مرحله صدور سند حسابداری فروش',
            'default' => 'after_invoice_approval',
            'options' => [
                'after_invoice_approval' => 'بعد از تایید فاکتور',
                'after_warehouse_issue' => 'بعد از خروج انبار',
                'after_delivery' => 'بعد از تحویل',
                'after_accountant_review' => 'بعد از بررسی حسابدار',
                'manual' => 'دستی',
            ],
        ],
        'voucher_status_after_sale' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'وضعیت سند حسابداری بعد از فروش',
            'default' => 'temporary',
            'options' => [
                'draft' => 'پیش نویس',
                'temporary' => 'موقت',
                'approved' => 'تایید شده',
                'permanent_after_review' => 'دائم بعد از بازبینی مالی',
            ],
        ],
        'crm_followup_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'اجبار پیگیری CRM در فرآیند فروش',
            'default' => 'optional',
            'options' => [
                'optional' => 'اختیاری',
                'required_before_invoice' => 'الزام پیگیری قبل از ثبت فاکتور',
                'required_after_invoice' => 'الزام پیگیری بعد از ثبت فاکتور',
                'required_until_settlement' => 'الزام پیگیری تا تسویه',
            ],
        ],
        'crm_automation_policy' => [
            'group' => 'sales_scenario',
            'type' => 'multiselect',
            'label' => 'اتوماسیون CRM در فرآیند فروش',
            'default' => ['task_after_invoice', 'task_after_card_move'],
            'options' => [
                'task_after_invoice' => 'ساخت پیگیری بعد از فاکتور',
                'task_after_card_move' => 'ساخت پیگیری بعد از جابجایی کارت کاریز',
                'task_after_rejection' => 'ساخت پیگیری بعد از رد فاکتور',
                'task_for_new_customer' => 'ساخت وظیفه برای مشتری جدید',
                'opportunity_required' => 'الزام فرصت فروش قبل از فاکتور',
                'lost_reason_required' => 'الزام دلیل باخت فرصت',
            ],
        ],
        'invoice_cancel_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'سیاست ابطال فاکتور فروش',
            'default' => 'manager_approval',
            'options' => [
                'creator_before_approval' => 'ثبت کننده قبل از تایید',
                'sales_manager' => 'مدیر فروش',
                'accountant_approval' => 'تایید حسابدار',
                'manager_approval' => 'تایید مدیر پنل',
            ],
        ],
        'sales_return_approval_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'سیاست تایید مرجوعی فروش',
            'default' => 'manager_warehouse_accounting',
            'options' => [
                'auto_before_delivery' => 'خودکار قبل از تحویل',
                'sales_manager' => 'تایید مدیر فروش',
                'warehouse_accounting' => 'تایید انبار و حسابداری',
                'manager_warehouse_accounting' => 'مدیر، انبار و حسابداری',
            ],
        ],
        'return_warehouse_policy' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'انبار مقصد مرجوعی فروش',
            'default' => 'source_store',
            'options' => [
                'source_store' => 'همان انبار خروج',
                'return_store' => 'انبار مرجوعی',
                'quality_control_store' => 'انبار کنترل کیفیت',
            ],
        ],
        'approval_sla_hours' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'مهلت تایید فروش ساعت',
            'default' => '24',
        ],
        'warehouse_sla_hours' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'مهلت اقدام انبار ساعت',
            'default' => '24',
        ],
        'accounting_sla_hours' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'مهلت بررسی حسابداری ساعت',
            'default' => '24',
        ],
        'crm_followup_sla_days' => [
            'group' => 'sales_scenario',
            'type' => 'number',
            'label' => 'مهلت پیگیری CRM روز',
            'default' => '3',
        ],
        'escalation_role' => [
            'group' => 'sales_scenario',
            'type' => 'select',
            'label' => 'نقش دریافت کننده هشدار تاخیر',
            'default' => 'panel_manager',
            'options' => [
                'leader' => 'سرپرست فروش',
                'sales_manager' => 'مدیر فروش',
                'accountant' => 'حسابدار',
                'warehouse_manager' => 'مدیر انبار',
                'panel_manager' => 'مدیر پنل',
            ],
        ],
        'notification_events_enabled' => [
            'group' => 'notification_sms',
            'type' => 'multiselect',
            'label' => 'عملیات هایی که اعلان هدر بفرستند',
            'default' => ['crm_card_created', 'crm_customer_card_created', 'crm_card_moved', 'crm_automation_followup_created', 'crm_task_started', 'crm_task_finished', 'crm_comment_mention', 'system_operation_logged'],
            'options' => [
                'crm_card_created' => 'ثبت کارت کاریز',
                'crm_customer_card_created' => 'افزودن مشتری به کاریز',
                'crm_card_moved' => 'جابجایی کارت کاریز',
                'crm_automation_followup_created' => 'ساخت پیگیری خودکار CRM',
                'crm_task_started' => 'شروع تسک',
                'crm_task_finished' => 'پایان تسک',
                'crm_comment_mention' => 'منشن در کامنت CRM',
                'system_operation_logged' => 'همه عملیات های ثبت شده در لاگ سیستم',
            ],
        ],
        'notification_operation_recipients' => [
            'group' => 'notification_sms',
            'type' => 'select',
            'label' => 'گیرندگان اعلان عملیات عمومی سیستم',
            'default' => 'panel_admins_actor',
            'options' => [
                'actor_only' => 'فقط انجام دهنده عملیات',
                'panel_admins' => 'مدیران پنل',
                'panel_admins_actor' => 'مدیران پنل و انجام دهنده عملیات',
                'all_active_users' => 'همه کاربران فعال پنل',
            ],
        ],
        'sms_events_enabled' => [
            'group' => 'notification_sms',
            'type' => 'multiselect',
            'label' => 'عملیات هایی که پیامک بفرستند',
            'default' => [],
            'options' => [
                'crm_card_created' => 'ثبت کارت کاریز',
                'crm_customer_card_created' => 'افزودن مشتری به کاریز',
                'crm_card_moved' => 'جابجایی کارت کاریز',
                'crm_automation_followup_created' => 'ساخت پیگیری خودکار CRM',
                'crm_task_started' => 'شروع تسک',
                'crm_task_finished' => 'پایان تسک',
                'crm_comment_mention' => 'منشن در کامنت CRM',
                'system_operation_logged' => 'همه عملیات های ثبت شده در لاگ سیستم',
            ],
        ],
        'sms_sender_number' => [
            'group' => 'notification_sms',
            'type' => 'text',
            'label' => 'شماره فرستنده کاوه نگار',
            'default' => '',
        ],
        'sms_unit_price_toman' => [
            'group' => 'notification_sms',
            'type' => 'number',
            'label' => 'هزینه هر پیامک تومان',
            'default' => '0',
        ],
        'sms_template_crm_card_created' => [
            'group' => 'notification_sms',
            'type' => 'textarea',
            'label' => 'متن پیامک ثبت کارت کاریز',
            'default' => 'کارت {card} در بورد {board} ثبت شد.',
        ],
        'sms_template_crm_customer_card_created' => [
            'group' => 'notification_sms',
            'type' => 'textarea',
            'label' => 'متن پیامک افزودن مشتری به کاریز',
            'default' => 'مشتری {card} به بورد {board} اضافه شد.',
        ],
        'sms_template_crm_card_moved' => [
            'group' => 'notification_sms',
            'type' => 'textarea',
            'label' => 'متن پیامک جابجایی کارت',
            'default' => 'کارت {card} از {from_list} به {to_list} منتقل شد.',
        ],
        'sms_template_crm_automation_followup_created' => [
            'group' => 'notification_sms',
            'type' => 'textarea',
            'label' => 'متن پیامک پیگیری خودکار CRM',
            'default' => 'پیگیری خودکار {followup} برای کارت {card} ساخته شد.',
        ],
        'sms_template_crm_task_started' => [
            'group' => 'notification_sms',
            'type' => 'textarea',
            'label' => 'متن پیامک شروع تسک',
            'default' => 'تسک {card} از ساعت {time} شروع شد.',
        ],
        'sms_template_crm_task_finished' => [
            'group' => 'notification_sms',
            'type' => 'textarea',
            'label' => 'متن پیامک پایان تسک',
            'default' => 'تسک {card} در ساعت {time} پایان یافت.',
        ],
        'sms_template_system_operation_logged' => [
            'group' => 'notification_sms',
            'type' => 'textarea',
            'label' => 'متن پیامک عملیات عمومی سیستم',
            'default' => '{operation} توسط {user} در بخش {section} ثبت شد.',
        ],
        'purchase_price_visibility' => [
            'group' => 'visibility',
            'type' => 'select',
            'label' => 'مشاهده قیمت خرید',
            'default' => 'manager',
            'options' => [
                'god' => 'فقط مدیر کل سیستم',
                'manager' => 'مدیر پنل و حسابدار',
                'all_admins' => 'همه مدیران',
            ],
        ],
        'profit_visibility' => [
            'group' => 'visibility',
            'type' => 'select',
            'label' => 'مشاهده سود',
            'default' => 'manager',
            'options' => [
                'god' => 'فقط مدیر کل سیستم',
                'manager' => 'مدیر پنل و حسابدار',
                'all_admins' => 'همه مدیران',
            ],
        ],
    ],

    'groups' => [
        'sales_workflow' => 'فروش و مشتریان',
        'sales_scenario' => 'سناریوی فروش',
        'logistics' => 'پخش و لجستیک',
        'warehouse' => 'انبار و کالا',
        'management' => 'مدیریت عملکرد',
        'finance' => 'مالی و حسابداری',
        'approval' => 'کنترل و تایید',
        'notification_sms' => 'اعلانات و پیامک ها',
        'visibility' => 'سطح مشاهده اطلاعات',
    ],
];
