<?php

/**
 * Build config/ui_icons.php from Tabler Icons (GitHub) + Font Awesome equivalents.
 * Run: php scripts/build-ui-icons.php
 */

$root = dirname(__DIR__);
$outFile = $root . '/config/ui_icons.php';

$names = array_unique(array_merge(
    explode(',', 'adjustments,alert-circle,alert-triangle,archive,arrow-down-circle,arrow-forward-up,arrow-left,arrow-right,arrows-transfer-up,barcode,bell,bolt,book,box,brand-angular,brand-css3,brand-figma,brand-html5,brand-javascript,brand-paypal,brand-react-native,briefcase,building-bank,building-store,building-warehouse,calendar,calendar-event,calendar-stats,cash,chart-arcs,chart-arrows-vertical,chart-bar,chart-dots,chart-line,chart-pie,chart-pie-2,check,checklist,checkup-list,chevron-down,chevron-left,circle-check,circle-filled,circle-half-2,clipboard-check,clock,clock-exclamation,color-swatch,columns,columns-3,confetti,copy,currency-dollar,device-floppy,device-gamepad-2,device-laptop,device-mobile,device-watch,diamond,dots,dots-vertical,download,edit,eye,eye-off,file,file-analytics,file-code-2,file-description,file-export,file-invoice,file-spreadsheet,file-text,folder,git-merge,grip-vertical,headset,history,home-2,info-circle,layout-dashboard,layout-grid,layout-kanban,list-check,list-details,mail,mail-opened,map,map-2,map-pin-off,menu-2,message-dots,moneybag,note,notebook,package,package-off,packages,paperclip,pencil,phone,photo,plus,printer,receipt,receipt-2,refresh,report-analytics,report-money,route,screen-share,search,settings,shield-check,ship,shoe,shopping-bag,shopping-cart,shopping-cart-plus,sparkles,star,target,thumb-down,thumb-up,ticket,trash,trending-up,truck,upload,user,user-check,user-exclamation,user-plus,users,user-search,users-plus,user-star,video,wallet,x,logout'),
    ['fa-edit', 'fa-refresh', 'fa-save', 'fa-sign-out', 'fa-trash']
));

$faMap = [
    'fa-edit' => 'edit',
    'fa-refresh' => 'refresh',
    'fa-save' => 'device-floppy',
    'fa-sign-out' => 'logout',
    'fa-trash' => 'trash',
];

$icons = [];
$failed = [];

foreach ($names as $name) {
    $name = trim($name);
    if ($name === '') {
        continue;
    }

    $fetchName = $faMap[$name] ?? $name;
    $url = "https://raw.githubusercontent.com/tabler/tabler-icons/v2.21.0/icons/{$fetchName}.svg";

    $ctx = stream_context_create(['http' => ['timeout' => 15, 'user_agent' => 'dokan-icon-builder']]);
    $svg = @file_get_contents($url, false, $ctx);

    if ($svg === false || $svg === '') {
        $failed[] = $name;
        continue;
    }

    if (!preg_match('/<svg[^>]*>(.*)<\/svg>/is', $svg, $m)) {
        $failed[] = $name;
        continue;
    }

    $inner = trim($m[1]);
    $inner = preg_replace('/\sstroke-width="[^"]*"/', ' stroke-width="2"', $inner);
    $icons[$name] = $inner;
}

ksort($icons);

$export = var_export($icons, true);
$php = <<<PHP
<?php

/**
 * Inline SVG paths for <x-ui.icon> — generated by scripts/build-ui-icons.php
 * Do not edit manually; re-run the script after adding new icon names.
 */
return {$export};

PHP;

file_put_contents($outFile, $php);

echo 'Built ' . count($icons) . ' icons -> config/ui_icons.php' . PHP_EOL;
if ($failed !== []) {
    echo 'Failed: ' . implode(', ', $failed) . PHP_EOL;
    exit(1);
}
